"""Added program group column

Revision ID: 02d91ea0fb3d
Revises: 776909fd29d0
Create Date: 2025-05-27 23:46:53.409740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d91ea0fb3d'
down_revision = '776909fd29d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_matrix_view',
    sa.Column('course_matrix_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('course_name', sa.String(length=100), nullable=True),
    sa.Column('course_code', sa.String(length=100), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('instructor_first_name', sa.String(length=100), nullable=True),
    sa.Column('instructor_last_name', sa.String(length=100), nullable=True),
    sa.Column('instructor_email', sa.String(length=100), nullable=True),
    sa.Column('instructor_title', sa.String(length=100), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('programme', sa.String(length=100), nullable=True),
    sa.Column('programme_code', sa.String(length=100), nullable=True),
    sa.Column('total_students', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('course_matrix_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_matrix_view')
    # ### end Alembic commands ###
