"""Added department_id to Students

Revision ID: 408deebfc205
Revises: 93362daa83b7
Create Date: 2025-05-25 11:29:18.259513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408deebfc205'
down_revision = '93362daa83b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
