"""Added program group column

Revision ID: 776909fd29d0
Revises: 408deebfc205
Create Date: 2025-05-27 22:57:59.296072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776909fd29d0'
down_revision = '408deebfc205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_matrix', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_group', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_matrix', schema=None) as batch_op:
        batch_op.drop_column('program_group')

    # ### end Alembic commands ###
